### ISSUE TITLE
Entry link not displaying in data editor but option is available in roster editor

### ISSUE THREAD

**Issue by FarseerVeraenthis** [giloushaker/nr-editor#10]
![image](https://github.com/giloushaker/nr-editor/assets/23246922/bdfe0623-9f04-42ca-ac11-f2f49118b9a1)
I added a link to the Warlord Shared Selection Entry for Azreal so he can be selected as Warlord.
The checkbox shows in Battlescribe and is selectable, but the link is not shown in the data editor, so I can't be certain it is there without using the roster editor!! 😄

**Comment by giloushaker** [comment]
Cant reproduce, is there any errors in the console?

If not, could you provide the files

**Comment by FarseerVeraenthis** [comment]
![image](https://github.com/giloushaker/nr-editor/assets/23246922/382fcf78-2bf6-4c0b-9553-c34fc593e306)

I closed an re-opened, issue is still present, opened the console and this is all that is in there... is this relevant??

**Comment by giloushaker** [comment]
Yes but im still not sure, Could you give me the data files and the exact steps your doing?

**Comment by FarseerVeraenthis** [comment]
data files are from the 10th ed repo, steps are to right click on Azrael, click 'Link', then type Warlord in the search box....

**Comment by FarseerVeraenthis** [comment]
same in Space Marines;
![image](https://github.com/giloushaker/nr-editor/assets/23246922/e724b14b-c7ba-4d58-99fe-59930cd46c96)

**Comment by giloushaker** [comment]
Where is the 10th ed repo?

**Comment by FarseerVeraenthis** [comment]
https://github.com/BSData/wh40k-10e

**Comment by giloushaker** [comment]
I get 404, im assuming its private and i dont have access

**Comment by FarseerVeraenthis** [comment]
it is private, you will need to ask in the Development channel for acess

**Comment by giloushaker** [comment]
I put out a release with an attempt to fix it

**Comment by FarseerVeraenthis** [comment]
that is fixed with the latest release - thanks for the quick turnaround!!
