### ISSUE TITLE
BUG: App does not correctly create or read InfoGroups

### ISSUE THREAD

**Issue by Mad-Spy** [giloushaker/nr-editor#16]
If a Shared InfoGroup is created in the NR-Editor, it cannot be parsed by the BS roster builder or data editor, and vice-versa.

There are examples in the current Chaos Space Marines catalogue in the wh40k-10e repo.

I initially added InfoGroups in NR-Editor, and they appeared to work correctly. However, the details were not displayed in the BS Roster Builder.

On opening the file in the BS Data Editor, the info groups were not displayed, and all the links to them were broken.

I then recreated the group in BS editor and relinked them and they display properly.

Reopening the file in NR-Editor shows no InfoGroups, although the links to them are still there.

**Comment by giloushaker** [comment]
Fixed in v1.1.71
Btw i dont have access to the wh40k-10e repo
