### ISSUE TITLE
v1.1.71: Odd behaviour when searching categories

### ISSUE THREAD

**Issue by Mad-Spy** [giloushaker/nr-editor#18]
![image](https://github.com/giloushaker/nr-editor/assets/29306451/bf449ae9-c799-4b49-ad1a-f56830b6decd)

When searching categories, categories which have been selected for the entry are also being pulled up by the search, but with an error flag to say that they can't be found.

Clearing the search box and checking "Only show selected categories" displays them without an error.

Note: this is not necessarily undesired behaviour in terms of always returning selected categories, but the error mark is definitely a bug.

**Comment by giloushaker** [comment]
Fixed in v1.1.72
