### ISSUE TITLE
REQUEST: Different icon for editor and builder

### ISSUE THREAD

**Issue by nstephenh** [giloushaker/nr-editor#21]
Could editor have a slightly different  app icon? When both programs are open in the windows taskbar it's hard to tell the difference.
Either a different color filter or maybe some free clipart of a hammer for the editor?
![image](https://github.com/giloushaker/nr-editor/assets/3454308/ce7d604f-e5e7-4995-b458-1e4a8912bb6e)

**Comment by giloushaker** [comment]
Added in v1.1.79
