### ISSUE TITLE
REQUEST: Text box different background color

### ISSUE THREAD

**Issue by nstephenh** [giloushaker/nr-editor#22]
The text box for rule descriptions is the same as the background, which does not imply editability:
![image](https://github.com/giloushaker/nr-editor/assets/3454308/53699d33-015f-42ff-aa03-b765945bb4a8)
Please make it the same background color as the dropdowns/unchecked checkboxes.

**Comment by nstephenh** [comment]
Same with characteristics:
![image](https://github.com/giloushaker/nr-editor/assets/3454308/eb315b48-a888-4075-b92c-88e35fb3778d)

**Comment by giloushaker** [comment]
Fixed in v1.1.79
