### ISSUE TITLE
REQUEST: Refs in conditions

### ISSUE THREAD

**Issue by nstephenh** [giloushaker/nr-editor#24]
Looking at the heresy data, it looks like "refs" doesn't pull references in conditions? I'd like to get a list of these if possible
I could be wrong

**Comment by giloushaker** [comment]
it does, just doesnt count them in the refs displayed
if you see something with 0 refs, it means they have only conditions/constraints/modifiers/repeats refs, eg `Clanfolk Cavalry (Fast)`
