### ISSUE TITLE
REQUEST: Links in Sort Order

### ISSUE THREAD

**Issue by nstephenh** [giloushaker/nr-editor#25]
Currently sort order appears to be:
Links of all types, alphabetically (including profiles)
Rules
Profiles
Entries 

I'd prefer if links sorted with whatever type they are pointing to, instead of with other links.

![image](https://github.com/giloushaker/nr-editor/assets/3454308/b5d0da99-258f-4660-88a5-0c55f36537b4)

**Comment by giloushaker** [comment]
Added in v1.1.81
