### ISSUE TITLE
catalogue link incomplete

### ISSUE THREAD

**Issue by AbonShell** [giloushaker/nr-editor#3]
When importing another catalog, it creates an incomplete link. It needs a type, default should be type="catalogue" regardless if the source is a library or not.

Link NR-editor creates:
`` <catalogueLink name="Imperium - Space Marines" id="da8e-75bd-17ec-90f8" targetId="e0af-67df-9d63-8fb7"/>``

Link expected
 ``<catalogueLink name="Imperium - Space Marines" id="da8e-75bd-17ec-90f8" targetId="e0af-67df-9d63-8fb7" type="catalogue"/>``

**Comment by giloushaker** [comment]
Fixed in 1.1.31
