### ISSUE TITLE
When creating a link, it creates this error

### ISSUE THREAD

**Issue by AbonShell** [giloushaker/nr-editor#4]
![image](https://github.com/giloushaker/nr-editor/assets/20672472/6f0ee6f2-b15e-425d-a70d-b8fe3ed4426c)

It creates a hidden, broken link with the name of Unknown

![image](https://github.com/giloushaker/nr-editor/assets/20672472/ae49cfe2-8ab7-4117-bf55-911ecbfd41e2)

**Comment by giloushaker** [comment]
can't reproduce this, but put a release out wich should fix it regardless (1.1.34)

**Comment by AbonShell** [comment]
yeah i couldnt really get it to happen on purpose. it normally only happened on accident
