### ISSUE TITLE
Clicking a typed entry on an infolink/link makes it disappear 

### ISSUE THREAD

**Issue by AbonShell** [giloushaker/nr-editor#6]
![image](https://github.com/giloushaker/nr-editor/assets/20672472/687bc8b4-68c0-48ad-90c5-efe62907cd6c)

A work around to it would be to first select an entry from the dropdown, then search for what you want.

If you try with the data already provided to you, steps for reproduction are:

Go to the Tyranid  Warrior and try adding a link for a bolt pistol by searching for it.

It will disapear

**Comment by giloushaker** [comment]
Fixed in 1.1.42
