### ISSUE TITLE
Copy and pasting only copies the top most entry

### ISSUE THREAD

**Issue by AbonShell** [giloushaker/nr-editor#7]
``{"parentKey":"selectionEntries","modifiers":[{"repeats":[{"field":"selections","scope":"a125-b6fb-2945-56a","value":3,"percentValue":false,"shared":true,"includeChildSelections":true,"includeChildForces":true,"childId":"model"}],"type":"increment","field":"363c-1318-44c0-3b60","value":1}],"constraints":[{"field":"selections","scope":"parent","value":0,"percentValue":false,"shared":true,"includeChildSelections":true,"includeChildForces":false,"id":"363c-1318-44c0-3b60","type":"max"}],"costs":[{"name":"pl","typeId":"c5fb-5b9b-89f6-86c","value":0},{"name":"pts","typeId":"51b2-306e-1021-d207","value":0}],"profiles":[{"characteristics":[{"$text":"36\"","name":"Range","typeId":"9896-9419-16a1-92fc"},{"$text":"D3","name":"A","typeId":"3bb-c35f-f54-fb08"},{"$text":"4+","name":"BS","typeId":"94d-8a98-cf90-183e"},{"$text":"9","name":"S","typeId":"2229-f494-25db-c5d3"},{"$text":"-2","name":"AP","typeId":"9ead-8a10-520-de15"},{"$text":"2","name":"D","typeId":"a354-c1c8-a745-f9e3"},{"$text":"Blast","name":"Keywords","typeId":"7f1b-8591-2fcf-d01c"}],"name":"Venom Cannon","hidden":false,"typeId":"f77d-b953-8fa4-b762","typeName":"Ranged Weapon","id":"dab5-25c0-6952-3a64"}],"infoLinks":[{"name":"Blast","type":"rule","id":"4c29-59ae-45e1-541d","targetId":"6c1f-1cf7-ff25-c99e"}],"id":"4368-5efe-817d-721b","name":"Venom Cannon","hidden":false,"collective":true,"import":true,"type":"upgrade"}`` only outputs
![image](https://github.com/giloushaker/nr-editor/assets/20672472/64ad6941-ae7c-4b21-8ec7-2dedfe9d671b)

**Comment by giloushaker** [comment]
Should be fixed in v1.1.44
