### ISSUE TITLE
Repeats get broken after saving and reopening

### ISSUE THREAD

**Issue by AbonShell** [giloushaker/nr-editor#8]
![image](https://github.com/giloushaker/nr-editor/assets/20672472/129ccf9e-201e-4838-9e71-ed8954c4c8f2)
![image](https://github.com/giloushaker/nr-editor/assets/20672472/21484c37-394d-49e4-b02c-b209b0ef415f)
And changing the value in the editor yields this
![image](https://github.com/giloushaker/nr-editor/assets/20672472/b0d07442-815f-4b7a-8180-cf1d07cbb430)

**Comment by giloushaker** [comment]
Fixed in 1.1.45
