### ISSUE TITLE
Auto-Update doesn't complete

### ISSUE THREAD

**Issue by FarseerVeraenthis** [giloushaker/nr-editor#9]
I downloaded v1.1.46, closed and reopened as suggested as a new release was made available.
On re-opening the update was found and appeared to be installed, but actually doesn't appear to have been as I got 100% in the top corner, the update popped up every time I closed/re-opened and the mouse cursor was with the spinny circle all the time when in the app.
![image](https://github.com/giloushaker/nr-editor/assets/23246922/3bad080c-9640-466f-8bde-4367f2fee1ed)
I had to manually download the installer again, when I did so Windows blocked the install initially as it say it is from an unknown publisher - this might be why the installer / auto-update could never complete.

**Comment by AbonShell** [comment]
Note this seems to only affect Windows? Its working fine for the appimage on linux

**Comment by giloushaker** [comment]
changed some stuff so hopefully it'll work better from 1.1.67 onwards

**Comment by FarseerVeraenthis** [comment]
I have manually downloaded and install 1.1.67 - I'll let you know if auto-update works after the next release :-)

**Comment by FarseerVeraenthis** [comment]
seem to be working now. version 1.1.67 auto-updated to 1.1.68 without any fuss! 😃
